name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-frontend:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-app/package-lock.json

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        working-directory: frontend-app
        run: npm install

      - name: Run frontend tests
        working-directory: frontend-app
        run: npm run test --if-present

      - name: Build the frontend app
        working-directory: frontend-app
        run: npm run tauri build

      - name: List build artifacts
        working-directory: frontend-app
        run: |
          echo "=== Checking bundle directory ==="
          ls -la src-tauri/target/release/bundle/ || echo "Bundle directory not found"
          echo "=== Checking target directory ==="
          ls -la src-tauri/target/release/ || echo "Release directory not found"
          echo "=== Checking target directory structure ==="
          find src-tauri/target -name "*.app" -o -name "*.dmg" -o -name "*.msi" -o -name "*.deb" 2>/dev/null || echo "No app files found"

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ matrix.platform }}
          path: |
            frontend-app/src-tauri/target/release/bundle/
            frontend-app/src-tauri/target/release/taury-crm*
          if-no-files-found: warn

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build backend
        working-directory: backend-app/backend-api
        run: |
          cargo build --release
          cargo test

      - name: Upload backend binary
        uses: actions/upload-artifact@v4
        with:
          name: backend-binary
          path: backend-app/backend-api/target/release/crm-backend-api

  build-python-sidecar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        working-directory: backend-app/sidecar-python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Python sidecar
        working-directory: backend-app/sidecar-python
        run: |
          python -m pytest tests/ || echo "No tests found"

      - name: Upload Python sidecar
        uses: actions/upload-artifact@v4
        with:
          name: python-sidecar
          path: backend-app/sidecar-python/

