name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-frontend:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend-app/package-lock.json

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        working-directory: frontend-app
        run: npm install

      - name: Run frontend tests
        working-directory: frontend-app
        run: npm run test --if-present

      - name: Build the frontend app
        working-directory: frontend-app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: frontend-v__VERSION__
          releaseName: 'Taury CRM Frontend v__VERSION__'
          releaseBody: |
            Frontend application for Taury CRM.
            
            ## Changes
            - Fixed timestamp synchronization
            - Fixed date display issues
            - Improved sync system
            - Separated frontend and backend
          releaseDraft: true
          prerelease: false

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build backend
        working-directory: backend-app/backend-api
        run: |
          cargo build --release
          cargo test

      - name: Create backend release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: backend-v${{ github.run_number }}
          name: Taury CRM Backend v${{ github.run_number }}
          body: |
            Backend API for Taury CRM.
            
            ## Installation
            1. Download the binary for your platform
            2. Set up PostgreSQL database
            3. Configure environment variables
            4. Run the binary
            
            ## Configuration
            ```bash
            DATABASE_URL=postgresql://user:password@localhost:5432/crm
            PORT=8080
            ```
          files: |
            backend-app/backend-api/target/release/crm-backend-api
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-python-sidecar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        working-directory: backend-app/sidecar-python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Python sidecar
        working-directory: backend-app/sidecar-python
        run: |
          python -m pytest tests/ || echo "No tests found"

      - name: Create Python sidecar release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sidecar-v${{ github.run_number }}
          name: Taury CRM Python Sidecar v${{ github.run_number }}
          body: |
            Python sidecar for document generation.
            
            ## Installation
            1. Install Python 3.9+
            2. Install dependencies: `pip install -r requirements.txt`
            3. Run: `python api.py`
          files: |
            backend-app/sidecar-python/
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-complete-release:
    needs: [build-frontend, build-backend, build-python-sidecar]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create complete release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Taury CRM Complete v${{ github.run_number }}
          body: |
            Complete Taury CRM application with frontend, backend, and sidecar.
            
            ## Components
            - **Frontend**: Desktop application (Windows, macOS, Linux)
            - **Backend**: API server (Rust)
            - **Sidecar**: Document generation (Python)
            
            ## Quick Start
            1. Download and install the frontend for your platform
            2. Set up the backend on your server (Raspberry Pi recommended)
            3. Configure the frontend to connect to your backend
            
            ## Documentation
            See `DEPLOYMENT.md` for detailed installation instructions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
